name: cedar
description: Core types and interfaces of the Cedar policy language in Dart.
version: 0.1.1
repository: https://github.com/celest-dev/celest/tree/main/packages/cedar

environment:
  sdk: ^3.3.0

dependencies:
  built_collection: ^5.1.1
  built_value: ^8.9.1
  collection: ^1.18.0
  json_annotation: ^4.8.1
  meta: ^1.11.0

dev_dependencies:
  build_runner: ^2.4.8
  built_value_generator: ^8.9.1
  lints: ^3.0.0
  test: ^1.24.0
