name: celest_test
description: Helper package for running integration tests with Celest.
version: 0.1.0
homepage: https://celest.dev
repository: https://github.com/celest-dev/celest/tree/main/packages/celest_test

environment:
  sdk: ^3.5.0
resolution: workspace

dependencies:
  async: ^2.11.0
  logging: ^1.3.0
  test: ^1.25.15
  vm_service: '>=14.0.0 <16.0.0'

dev_dependencies:
  celest_lints: ^1.0.0
