name: openai_example_client
description: The Celest client for openai_example.
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  celest_backend:
    path: ..
  celest: '^1.0.0-0'
  celest_core: '^1.0.0-0'
  meta: '^1.12.0'
  native_storage: '^0.2.2'

dev_dependencies: {}

dependency_overrides:
  celest:
    path: ../../../../packages/celest
  celest_core:
    path: ../../../../packages/celest_core
  celest_auth:
    path: ../../../../packages/celest_auth
  celest_cloud:
    path: ../../../../packages/celest_cloud
