name: celest_dev
publish_to: none

environment:
  sdk: ^3.7.0

workspace:
  - apps/cli
  - packages/celest
  - packages/celest_ast
  - packages/celest_auth
  - packages/celest_cloud
  - packages/celest_core
  - packages/celest_db_studio
  - packages/celest_lints
  - packages/celest_test
  - services/celest_cloud_auth
  - services/celest_cloud_core
  - services/celest_cloud_hub

dependencies:
  drift: '>=2.26.1 <2.27.0'

dev_dependencies:
  drift_dev: '>=2.26.1 <2.27.0'
  melos: ^6.3.2
