name: celest_dev
publish_to: none

environment:
  sdk: ^3.5.0

workspace:
  - apps/cli
  - packages/celest
  - packages/celest_ast
  - packages/celest_auth
  - packages/celest_cloud
  - packages/celest_core
  - packages/celest_lints
  - packages/celest_test
  - services/celest_cloud_auth
  - services/celest_cloud_hub

dev_dependencies:
  melos: ^5.3.0
