name: celest_backend
description: The Celest backend for celest_project.
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  celest: ^1.0.0
  celest_ast: ^0.1.0
  celest_core: ^1.0.0
  google_generative_ai: ^0.2.0
  http: '>=0.13.0 <2.0.0'
  meta: ^1.12.0

dependency_overrides:
  celest:
    path: ../../../packages/celest
  celest_ast:
    path: ../../../packages/celest_ast
  celest_auth:
    path: ../../../packages/celest_auth
  celest_cloud:
    path: ../../../packages/celest_cloud
  celest_core:
    path: ../../../packages/celest_core

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.0
