name: celest_backend
description: The Celest backend for celest_project.
publish_to: none

environment:
  sdk: ^3.3.0

dependencies:
  celest: ^0.4.0-0
  google_generative_ai: ^0.2.0
  http: ">=0.13.0 <2.0.0"

dependency_overrides:
  celest:
    path: ../../../packages/celest
  celest_auth:
    path: ../../../packages/celest_auth
  celest_core:
    path: ../../../packages/celest_core
  corks_cedar:
    path: ../../../packages/corks_cedar
  native_storage:
    path: ../../../packages/native/storage

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
