name: cedar_ffi
description: FFI bindings for the Cedar policy language, written in Rust.
version: 0.1.1
repository: https://github.com/celest-dev/celest/tree/main/packages/cedar_ffi

environment:
  sdk: ^3.3.0

dependencies:
  built_collection: ^5.1.1
  built_value: ^8.9.1
  cedar: ^0.1.1
  cli_config: ^0.1.1
  collection: ^1.18.0
  ffi: ^2.1.0
  json_annotation: ^4.8.1
  logging: ^1.2.0
  meta: ^1.12.0
  native_assets_cli: ^0.4.2
  native_toolchain_c: ^0.3.4+1

dev_dependencies:
  build_runner: ^2.4.8
  built_value_generator: ^8.9.1
  ffigen: ^11.0.0
  json_serializable: ^6.7.1
  lints: ^3.0.0
  path: ^1.8.3
  test: ^1.21.0

ffigen:
  name: CedarFfi
  description: C bindings to the Cedar policy engine
  ffi-native:
  language: c
  headers:
    entry-points:
      - "src/include/bindings.h"
  compiler-opts:
    # Suppress nullability warnings on macOS
    - "-Wno-nullability-completeness"
    # Ignore warnings about availability macro
    - "-Wno-availability"
  output:
    bindings: "lib/src/ffi/cedar_bindings.g.dart"
  comments:
    style: any
    length: full
  exclude-all-by-default: true
  functions:
    include:
      - "cedar_.*"
    leaf:
      # All C APIs are leaf functions (e.g. they do not call into Dart)
      include:
        - ".*"
  structs:
    include:
      - "CCedar.*"
