name: cedar_ffi
description: FFI bindings for the Cedar policy language, written in Rust.
version: 0.1.1
repository: https://github.com/celest-dev/celest/tree/main/packages/cedar_ffi

environment:
  sdk: ^3.3.0

dependencies:
  built_collection: ^5.1.1
  built_value: ^8.9.1
  cedar: ^0.1.1
  cli_config: ">=0.1.1 <0.3.0"
  collection: ^1.18.0
  ffi: ^2.1.0
  json_annotation: ^4.8.1
  logging: ^1.2.0
  meta: ^1.12.0
  native_assets_cli: ^0.5.0
  native_toolchain_c: ^0.4.0

dev_dependencies:
  build_runner: ^2.4.8
  built_value_generator: ^8.9.1
  ffigen: ^11.0.0
  json_serializable: ^6.7.1
  lints: ^3.0.0
  path: ^1.8.3
  test: ^1.21.0
