name: localhost
description: A package that allows you to discover services on your local network using mDNS.
version: 1.0.0
repository: https://github.com/celest-dev/celest/tree/main/packages/localhost

environment:
  sdk: ^3.2.0

dependencies:
  async: ^2.11.0
  ffi: ^2.1.0
  logging: ^1.2.0
  os_detect: ^2.0.1
  stream_transform: ^2.1.0

dev_dependencies:
  ffigen: ^11.0.0
  lints: ^3.0.0
  test: ^1.24.0
