name: localhost
description: A package that allows you to discover services on your local network using mDNS.
version: 1.0.0
repository: https://github.com/celest-dev/celest/tree/main/packages/localhost

environment:
  sdk: ^3.2.0

dependencies:
  async: ^2.11.0
  ffi: ^2.1.0
  logging: ^1.2.0
  meta: ^1.12.0
  os_detect: ^2.0.1
  stream_transform: ^2.1.0

dev_dependencies:
  # TODO(dnys1): Use ^12.0.0 when released
  # Needed to support global fields.
  ffigen:
    git:
      url: https://github.com/dart-lang/native
      path: pkgs/ffigen
  lints: ^3.0.0
  multicast_dns: ^0.3.2+6
  shelf: ^1.4.1
  test: ^1.24.0
