name: celest_backend
description: The Celest backend for firebase_test.
publish_to: none

environment:
  sdk: ^3.7.0

dependencies:
  celest: ^1.0.0
  celest_core: ^1.0.0
  meta: ^1.12.0

dependency_overrides:
  celest:
    path: ../../../packages/celest
  celest_ast:
    path: ../../../packages/celest_ast
  celest_auth:
    path: ../../../packages/celest_auth
  celest_cloud:
    path: ../../../packages/celest_cloud
  celest_core:
    path: ../../../packages/celest_core
  celest_db_studio:
    path: ../../../packages/celest_db_studio

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.0
