name: corks
description: A starting point for Dart libraries or applications.
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.3.0

dependencies:
  cedar_core:
    path: ../cedar_core
  crypto: ^3.0.3
  fixnum: ^1.1.0
  meta: ^1.10.0
  protobuf: ^3.1.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
