// Generated by Celest. This file should not be modified manually, but
// it can be checked into version control.
// ignore_for_file: type=lint, unused_local_variable, unnecessary_cast, unnecessary_import, deprecated_member_use

library; // ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _$async;
import 'dart:convert' as _$convert;

import 'package:celest/celest.dart' as _$celest;
import 'package:celest_backend/models.dart';
import 'package:celest_core/celest_core.dart' as _$celest;
import 'package:celest_core/src/exception/cloud_exception.dart' as _$celest;
import 'package:celest_core/src/exception/serialization_exception.dart'
    as _$celest;
import 'package:openai_example_client/openai_example_client.dart';

class CelestFunctions {
  final openAi = CelestFunctionsOpenAi();
}

class CelestFunctionsOpenAi {
  Never _throwError({
    required int? $statusCode,
    required Map<String, Object?> $body,
  }) {
    final $error = ($body['@error'] as Map<String, Object?>?);
    $statusCode ??= ($error?['status'] as num?)?.toInt();
    final $code = ($error?['code'] as String);
    final $message = ($body['message'] as String?);
    final $details = ($body['@'] as _$celest.JsonValue?) ??
        ($body['details'] as _$celest.JsonMap?);
    switch ($code) {
      case r'dart.convert.JsonUnsupportedObjectError':
        throw _$celest.Serializers.instance
            .deserialize<_$convert.JsonUnsupportedObjectError>($body);
      case r'dart.async.AsyncError':
        throw _$celest.Serializers.instance
            .deserialize<_$async.AsyncError>($body);
      case r'dart.async.TimeoutException':
        throw _$celest.Serializers.instance
            .deserialize<_$async.TimeoutException>($body);
      case r'dart.core.Error':
        throw _$celest.Serializers.instance.deserialize<Error>($body);
      case r'dart.core.AssertionError':
        throw _$celest.Serializers.instance.deserialize<AssertionError>($body);
      case r'dart.core.TypeError':
        throw _$celest.Serializers.instance.deserialize<TypeError>($body);
      case r'dart.core.ArgumentError':
        throw _$celest.Serializers.instance.deserialize<ArgumentError>($body);
      case r'dart.core.RangeError':
        throw _$celest.Serializers.instance.deserialize<RangeError>($body);
      case r'dart.core.IndexError':
        throw _$celest.Serializers.instance.deserialize<IndexError>($body);
      case r'dart.core.UnsupportedError':
        throw _$celest.Serializers.instance
            .deserialize<UnsupportedError>($body);
      case r'dart.core.UnimplementedError':
        throw _$celest.Serializers.instance
            .deserialize<UnimplementedError>($body);
      case r'dart.core.StateError':
        throw _$celest.Serializers.instance.deserialize<StateError>($body);
      case r'dart.core.ConcurrentModificationError':
        throw _$celest.Serializers.instance
            .deserialize<ConcurrentModificationError>($body);
      case r'dart.core.OutOfMemoryError':
        throw _$celest.Serializers.instance
            .deserialize<OutOfMemoryError>($body);
      case r'dart.core.StackOverflowError':
        throw _$celest.Serializers.instance
            .deserialize<StackOverflowError>($body);
      case r'dart.core.FormatException':
        throw _$celest.Serializers.instance.deserialize<FormatException>($body);
      case r'dart.core.IntegerDivisionByZeroException':
        throw _$celest.Serializers.instance
            .deserialize<IntegerDivisionByZeroException>($body);
      case r'celest.core.v1.CloudException':
        throw _$celest.Serializers.instance
            .deserialize<_$celest.CloudException>($body);
      case r'celest.core.v1.CancelledException':
        throw _$celest.Serializers.instance
            .deserialize<_$celest.CancelledException>($body);
      case r'celest.core.v1.UnknownError':
        throw _$celest.Serializers.instance
            .deserialize<_$celest.UnknownError>($body);
      case r'celest.core.v1.BadRequestException':
        throw _$celest.Serializers.instance
            .deserialize<_$celest.BadRequestException>($body);
      case r'celest.core.v1.UnauthorizedException':
        throw _$celest.Serializers.instance
            .deserialize<_$celest.UnauthorizedException>($body);
      case r'celest.core.v1.NotFoundException':
        throw _$celest.Serializers.instance
            .deserialize<_$celest.NotFoundException>($body);
      case r'celest.core.v1.AlreadyExistsException':
        throw _$celest.Serializers.instance
            .deserialize<_$celest.AlreadyExistsException>($body);
      case r'celest.core.v1.PermissionDeniedException':
        throw _$celest.Serializers.instance
            .deserialize<_$celest.PermissionDeniedException>($body);
      case r'celest.core.v1.ResourceExhaustedException':
        throw _$celest.Serializers.instance
            .deserialize<_$celest.ResourceExhaustedException>($body);
      case r'celest.core.v1.FailedPreconditionException':
        throw _$celest.Serializers.instance
            .deserialize<_$celest.FailedPreconditionException>($body);
      case r'celest.core.v1.AbortedException':
        throw _$celest.Serializers.instance
            .deserialize<_$celest.AbortedException>($body);
      case r'celest.core.v1.OutOfRangeException':
        throw _$celest.Serializers.instance
            .deserialize<_$celest.OutOfRangeException>($body);
      case r'celest.core.v1.UnimplementedError':
        throw _$celest.Serializers.instance
            .deserialize<_$celest.UnimplementedError>($body);
      case r'celest.core.v1.InternalServerError':
        throw _$celest.Serializers.instance
            .deserialize<_$celest.InternalServerError>($body);
      case r'celest.core.v1.UnavailableError':
        throw _$celest.Serializers.instance
            .deserialize<_$celest.UnavailableError>($body);
      case r'celest.core.v1.DataLossError':
        throw _$celest.Serializers.instance
            .deserialize<_$celest.DataLossError>($body);
      case r'celest.core.v1.DeadlineExceededError':
        throw _$celest.Serializers.instance
            .deserialize<_$celest.DeadlineExceededError>($body);
      case r'celest.core.v1.SerializationException':
        throw _$celest.Serializers.instance
            .deserialize<_$celest.SerializationException>($body);
      default:
        throw _$celest.CloudException.http(
          status: $statusCode,
          code: $code,
          message: $message,
          details: $details,
        );
    }
  }

  /// Returns a list of available models.
  @_$celest.CloudFunction(
    api: 'open_ai',
    function: 'availableModels',
  )
  Future<List<String>> availableModels() async {
    final $response = await celest.httpClient.post(
      celest.baseUri.resolve('/open-ai/available-models'),
      headers: {'Content-Type': 'application/json; charset=utf-8'},
    );
    final $body = _$convert.jsonDecode($response.body);
    if ($response.statusCode != 200) {
      _throwError(
        $statusCode: $response.statusCode,
        $body: $body,
      );
    }
    return ($body as Iterable<Object?>).map((el) => (el as String)).toList();
  }

  /// Prompts the GPT [model] with the given [prompt] and [parameters].
  ///
  /// Returns the generated text.
  @_$celest.CloudFunction(
    api: 'open_ai',
    function: 'openAIRequest',
  )
  Stream<String> openAiRequest({
    required String model,
    required String prompt,
    ModelParameters parameters = const ModelParameters(),
  }) {
    final $channel = celest.eventClient
        .connect(celest.baseUri.resolve('/open-ai/open-a-i-request'));
    $channel.sink.add({
      r'model': model,
      r'prompt': prompt,
      r'parameters':
          _$celest.Serializers.instance.serialize<ModelParameters>(parameters),
    });
    return $channel.stream.map(($event) {
      if ($event is Map<String, Object?> && $event.containsKey('@error')) {
        _throwError($statusCode: -1, $body: $event);
      }
      return ($event as String);
    });
  }
}
