targets:
  $default:
    builders:
      drift_dev:
        enabled: false
      
      drift_dev:analyzer:
        enabled: true
        generate_for:
          - lib/src/database/**
          - test/database/wrapper/**
        options: &options
          databases:
            auth_database: lib/src/database/auth_database.dart
            test_database: test/database/wrapper/wrapper_database.dart
          schema_dir: drift_schema/
          test_dir: test/database/

          named_parameters: true
          store_date_time_values_as_text: false

          sql:
            dialect: sqlite
            options:
              version: "3.38"
              modules:
                - json1
          
          # Reduces generated code
          skip_verification_code: true
          data_class_to_companions: false

      drift_dev:modular:
        enabled: true
        generate_for:
          - lib/src/database/**
          - test/database/wrapper/**
        options: *options
