name: celest_db_studio
description: A wrapper over Outerbase Studio for Celest databases.
version: 0.1.0

environment:
  sdk: ^3.7.0
resolution: workspace

dependencies:
  celest_core: ^1.0.3-wip
  drift: ^2.26.1
  drift_hrana: ^1.0.5
  embed_annotation: ^1.2.2
  hrana: ^0.4.1
  shelf: ^1.4.0
  shelf_router: ^1.1.4
  sqlite3: ^2.7.5

dev_dependencies:
  build_runner: ^2.4.15
  celest_lints: ^1.1.0
  docker_process: ^1.3.2
  embed: ^1.4.1
  http: ^1.1.0
  test: ^1.24.0
  webdriver: ^3.1.0
