name: celest_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.3.0
  flutter: ">=3.19.0"

dependencies:
  celest_backend:
    path: celest/
  flutter:
    sdk: flutter
  logger: ^2.0.0

dependency_overrides:
  celest:
    path: ../../packages/celest
  celest_auth:
    path: ../../packages/celest_auth
  celest_core:
    path: ../../packages/celest_core
  native_storage:
    path: ../../packages/native/storage

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
