name: celest_project
description: An example of how to use OpenAI from Celest.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.3.0
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  logger: ^2.0.0
  openai_example_client:
    path: celest/client/

dependency_overrides:
  celest:
    path: ../../packages/celest
  celest_auth:
    path: ../../packages/celest_auth
  celest_cloud:
    path: ../../packages/celest_cloud
  celest_core:
    path: ../../packages/celest_core
  celest_db_studio:
    path: ../../packages/celest_db_studio

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
