name: celest_auth_example_client
description: The Celest client for celest_auth_example.
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  celest: ^1.0.0
  celest_backend:
    path: ../
  celest_core: ^1.0.0
  http: ^1.0.0
  meta: ^1.12.0
  native_storage: ^0.2.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.0
dependency_overrides:
  celest:
    path: ../../../../celest
  celest_ast:
    path: ../../../../celest_ast
  celest_auth:
    path: ../../..
  celest_cloud:
    path: ../../../../celest_cloud
  celest_cloud_auth:
    path: ../../../../../services/celest_cloud_auth
  celest_cloud_core:
    path: ../../../../../services/celest_cloud_core
  celest_core:
    path: ../../../../celest_core
