name: celest_auth_example_client
description: The Celest client for celest_auth_example.
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  celest: ^0.5.0-0
  celest_backend:
    path: ../
  celest_core: ^0.5.0-0
  http: ">=0.13.0 <2.0.0"
  native_storage: ^0.2.2

dev_dependencies:
  test:
