name: native_storage
description: A Dart-only package for accessing platform-native storage functionality.
version: 0.1.4
repository: https://github.com/celest-dev/celest/tree/main/packages/native/storage

environment:
  sdk: ^3.3.0
  flutter: ">=3.19.0"

# Explicitly declare platform support to help `pana`
platforms:
  web:
  windows:
  macos:
  linux:
  ios:
  android:

dependencies:
  ffi: ^2.1.2
  jni: ^0.8.0
  logging: ^1.2.0
  meta: ^1.11.0
  path: ^1.9.0
  stack_trace: ^1.11.1
  stream_channel: ^2.1.2
  web: ^0.5.1
  win32: ^5.4.0
  win32_registry: ^1.1.2
  windows_applicationmodel: ^0.2.0
  xdg_directories: ^1.0.4

dev_dependencies:
  # Uncomment to run ffigen. Breaks CI for windows.
  # TODO(dnys1): Use ^12.0.0 when released
  # Needed to support global fields.
  # ffigen:
  #   git:
  #     url: https://github.com/dart-lang/native
  #     path: pkgs/ffigen
  jnigen: ^0.8.0
  lints: ^3.0.0
  test: ^1.24.0

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
