include: package:celest_lints/library.yaml

analyzer:
  exclude:
    - '**/*.pb.dart'
    - '**/*.pbenum.dart'
    - '**/*.pbjson.dart'
  errors:
    avoid_unused_constructor_parameters: ignore
    camel_case_types: ignore
    implementation_imports: ignore
    public_member_api_docs: ignore
