[package]
name = "cedar-ffi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = { version = "1.0.81" }
cedar-policy = { path = "../third_party/cedar/cedar-policy" }
log = "0.4.21"
once_cell = "1.19.0"
serde = "1.0.197"
serde_json = "1.0.114"
simple_logger = "4.3.3"

[build-dependencies]
build-target = "0.4.0"
cbindgen = "0.26"
wasm-pack = "0.12.1"

[dev-dependencies]
wasm-bindgen-test = "0.3.42"
