// Generated by Celest. This file should not be modified manually, but
// it can be checked into version control.
// ignore_for_file: type=lint, unused_local_variable, unnecessary_cast, unnecessary_import

library; // ignore_for_file: no_leading_underscores_for_library_prefixes

import 'package:celest_auth/celest_auth.dart' as _$celest_auth;
import 'package:celest_auth/src/auth_impl.dart' as _$auth_impl;
import 'package:celest_core/_internal.dart';

extension type CelestAuth._(_$auth_impl.AuthImpl _hub)
    implements _$celest_auth.Auth {
  CelestAuth(
    CelestBase celest, {
    required SecureStorage secureStorage,
  }) : _hub = _$auth_impl.AuthImpl(
          celest,
          secureStorage: secureStorage,
        );

  _$auth_impl.Email get email => _$auth_impl.Email(_hub);
}
