include: package:celest_lints/app.yaml

analyzer:
  errors:
    avoid_print: ignore
    implementation_imports: ignore
  exclude:
    - lib/src/proto/**
    - lib/src/**/*.g.dart
    - test/database/*/generated/**
