targets:
  $default:
    builders:
      drift_dev:
        options:
          sql:
            dialect: sqlite
            options:
              version: "3.38"

          named_parameters: true
          store_date_time_values_as_text: false
