targets:
  $default:
    builders:
      drift_dev:
        # disable drift's default builder, we're using the modular setup
        # instead.
        enabled: false

      # Instead, enable drift_dev:analyzer and drift_dev:modular manually:
      drift_dev:analyzer:
        enabled: true
        generate_for:
          - lib/src/database/**
          - lib/src/model/**
        options: &options
          sql:
            dialect: sqlite
            options:
              version: "3.38"

          named_parameters: true
          store_date_time_values_as_text: false
      drift_dev:modular:
        enabled: true
        generate_for:
          - lib/src/database/**
          - lib/src/model/**
        # We use yaml anchors to give the two builders the same options
        options: *options
