name: celest_cloud_hub
description: A hub for managing the provisioning and deployment of Celest projects in the cloud.
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.7.0
resolution: workspace

dependencies:
  archive: ^4.0.6
  async: ^2.13.0
  cedar: ^0.2.4
  celest: ^1.0.0
  celest_ast: ^0.1.0
  celest_cli: ^1.0.0
  celest_cloud: ^0.1.0
  celest_cloud_auth: ^0.3.0-0
  celest_cloud_core: ^0.1.0
  celest_core: ^1.0.0
  collection: ^1.19.1
  convert: ^3.1.2
  corks_cedar: ^0.2.3
  crypto: ^3.0.6
  drift: '>=2.26.0 <2.27.0'
  file: ^7.0.1
  fixnum: ^1.1.1
  graphql: ^5.2.1
  grpc: ^4.0.1
  http: ^1.1.0
  json_annotation: ^4.9.0
  logging: ^1.3.0
  meta: ^1.16.0
  path: ^1.9.1
  process: ^5.0.3
  protobuf: ^3.1.0
  pub_semver: ^2.2.0
  sentry: ^8.14.1
  sentry_logging: ^8.14.1
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  sqlite3: ^2.7.5
  stack_trace: ^1.12.1
  yaml: ^3.1.3

dev_dependencies:
  build_runner: ^2.4.15
  celest_lints: ^1.0.0
  checks: ^0.3.0
  drift_dev: '>=2.26.0 <2.27.0'
  freezed: ^2.5.8
  json_serializable: ^6.9.4
  test: ^1.24.0
