name: celest_cloud_hub
description: A hub for managing the provisioning and deployment of Celest projects in the cloud.
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.7.0
resolution: workspace

dependencies:
  async: ^2.13.0
  cedar: ^0.2.4
  celest: ^1.0.0
  celest_ast: ^0.1.0
  celest_cloud: ^0.1.0
  celest_cloud_auth: ^0.3.0-0
  celest_core: ^1.0.0
  collection: ^1.19.1
  corks_cedar: ^0.2.3
  crypto: ^3.0.6
  drift: '>=2.26.0 <2.27.0'
  fixnum: ^1.1.1
  grpc: ^4.0.1
  http: ^1.1.0
  logging: ^1.3.0
  meta: ^1.16.0
  protobuf: ^3.1.0
  pub_semver: ^2.2.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  sqlite3: ^2.7.5

dev_dependencies:
  build_runner: ^2.4.15
  celest_lints: ^1.0.0
  drift_dev: '>=2.26.0 <2.27.0'
  path: ^1.9.1
  test: ^1.24.0
