// Generated by Celest. This file should not be modified manually, but
// it can be checked into version control.
// ignore_for_file: type=lint, unused_local_variable, unnecessary_cast, unnecessary_import

library; // ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:convert' as _$convert;

import 'package:celest/celest.dart';
import 'package:celest_backend/exceptions.dart' as _$exceptions;
import 'package:celest_backend/models.dart' as _$models;

import '../../client.dart';

class CelestFunctions {
  final tasks = CelestFunctionsTasks();
}

class CelestFunctionsTasks {
  Never _throwError({
    required int $statusCode,
    required Map<String, Object?> $body,
  }) {
    final $error = ($body['error'] as Map<String, Object?>);
    final $code = ($error['code'] as String);
    final $details = ($error['details'] as Map<String, Object?>?);
    switch ($code) {
      case r'ServerException':
        throw Serializers.instance
            .deserialize<_$exceptions.ServerException>($details);
      case _:
        switch ($statusCode) {
          case 400:
            throw BadRequestException($code);
          case _:
            throw InternalServerException($code);
        }
    }
  }

  Future<Map<String, _$models.Task>> listAllTasks() async {
    final $response = await celest.httpClient.post(
      celest.baseUri.resolve('/tasks/list-all-tasks'),
      headers: const {'Content-Type': 'application/json; charset=utf-8'},
    );
    final $body =
        (_$convert.jsonDecode($response.body) as Map<String, Object?>);
    if ($response.statusCode != 200) {
      _throwError(
        $statusCode: $response.statusCode,
        $body: $body,
      );
    }
    return ($body['response'] as Map<String, Object?>).map((
      key,
      value,
    ) =>
        MapEntry(
          key,
          Serializers.instance.deserialize<_$models.Task>(value),
        ));
  }

  Future<void> addTask({
    required String title,
    required _$models.Importance importance,
  }) async {
    final $response = await celest.httpClient.post(
      celest.baseUri.resolve('/tasks/add-task'),
      headers: const {'Content-Type': 'application/json; charset=utf-8'},
      body: _$convert.jsonEncode({
        r'title': title,
        r'importance':
            Serializers.instance.serialize<_$models.Importance>(importance),
      }),
    );
    final $body =
        (_$convert.jsonDecode($response.body) as Map<String, Object?>);
    if ($response.statusCode != 200) {
      _throwError(
        $statusCode: $response.statusCode,
        $body: $body,
      );
    }
    return;
  }

  Future<void> deleteTask({required String id}) async {
    final $response = await celest.httpClient.post(
      celest.baseUri.resolve('/tasks/delete-task'),
      headers: const {'Content-Type': 'application/json; charset=utf-8'},
      body: _$convert.jsonEncode({r'id': id}),
    );
    final $body =
        (_$convert.jsonDecode($response.body) as Map<String, Object?>);
    if ($response.statusCode != 200) {
      _throwError(
        $statusCode: $response.statusCode,
        $body: $body,
      );
    }
    return;
  }

  Future<void> markAsCompleted({required String id}) async {
    final $response = await celest.httpClient.post(
      celest.baseUri.resolve('/tasks/mark-as-completed'),
      headers: const {'Content-Type': 'application/json; charset=utf-8'},
      body: _$convert.jsonEncode({r'id': id}),
    );
    final $body =
        (_$convert.jsonDecode($response.body) as Map<String, Object?>);
    if ($response.statusCode != 200) {
      _throwError(
        $statusCode: $response.statusCode,
        $body: $body,
      );
    }
    return;
  }

  Future<void> markAsIncomplete({required String id}) async {
    final $response = await celest.httpClient.post(
      celest.baseUri.resolve('/tasks/mark-as-incomplete'),
      headers: const {'Content-Type': 'application/json; charset=utf-8'},
      body: _$convert.jsonEncode({r'id': id}),
    );
    final $body =
        (_$convert.jsonDecode($response.body) as Map<String, Object?>);
    if ($response.statusCode != 200) {
      _throwError(
        $statusCode: $response.statusCode,
        $body: $body,
      );
    }
    return;
  }
}
