include: package:celest_lints/library.yaml

analyzer:
  errors:
    implementation_imports: ignore
    public_member_api_docs: ignore
  exclude:
    - '**/*.pb.dart'
    - '**/*.pbenum.dart'
    - '**/*.pbjson.dart'
