name: celest_backend
description: The Celest backend for celest_project.
publish_to: none

environment:
  sdk: ^3.3.0

dependencies:
  celest: ^0.4.0
  chat_gpt_sdk: ^2.2.8
  http: ">=0.13.0 <2.0.0"

dependency_overrides:
  celest:
    path: ../../../packages/celest
  celest_auth:
    path: ../../../packages/celest_auth
  celest_cloud:
    path: ../../../packages/celest_cloud
  celest_core:
    path: ../../../packages/celest_core

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.0
