// Generated by Celest. This file should not be modified manually, but
// it can be checked into version control.
// ignore_for_file: type=lint, unused_local_variable, unnecessary_cast, unnecessary_import

library; // ignore_for_file: no_leading_underscores_for_library_prefixes

import 'package:celest/celest.dart' as _i1;
import 'package:celest_backend/models.dart' as _i2;

abstract final class apis {
  static const openAi = _i1.CloudApi(name: r'open_ai');
}

abstract final class functions {
  static const openAiAvailableModels = _i1.CloudFunction<void, List<String>>(
    api: r'open_ai',
    functionName: r'availableModels',
  );

  static const openAiOpenAiRequest = _i1.CloudFunction<
      ({
        String prompt,
        String model,
        _i2.ModelParameters parameters,
        String openApiKey
      }),
      String>(
    api: r'open_ai',
    functionName: r'openAIRequest',
  );

  static const openAiSayHelloDelete =
      _i1.CloudFunction<(String, {String openApiKey}), String>(
    api: r'open_ai',
    functionName: r'sayHelloDelete',
  );
}

abstract final class env {
  static const openApiKey = _i1.EnvironmentVariable(name: r'OPEN_API_KEY');
}
