name: celest_backend
description: The Celest backend for todo.
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  celest: ^1.0.0
  celest_core: ^1.0.0
  drift: '>=2.26.0 <2.27.0'
  drift_hrana: ^1.0.2
  meta: ^1.12.0

dependency_overrides:
  celest:
    path: ../../../packages/celest
  celest_ast:
    path: ../../../packages/celest_ast
  celest_auth:
    path: ../../../packages/celest_auth
  celest_cloud:
    path: ../../../packages/celest_cloud
  celest_core:
    path: ../../../packages/celest_core

dev_dependencies:
  build_runner: ^2.4.13
  drift_dev: '>=2.26.0 <2.27.0'
  lints: ^5.0.0
  test: ^1.25.0
