name: celest_backend
description: The Celest backend for todo.
publish_to: none

environment:
  sdk: ^3.2.0

dependencies:
  celest: ^0.1.0
  celest_core: ^0.1.0
  http: ">=0.13.0 <2.0.0"
  uuid: ^4.3.3

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
