// Generated by `celest start`. This file should not be modified manually, but
// it can be checked into version control.

library;

const $_CelestResources resources = $_CelestResources();

final class $_CelestResources {
  const $_CelestResources();
}
