// Generated by `celest start`. This file should not be modified manually, but
// it can be checked into version control.

library; // ignore_for_file: no_leading_underscores_for_library_prefixes

import 'package:celest/celest.dart' as _i1;

List<_i1.CloudWidget> forEnvironment(String environment) {
  const base = <_i1.CloudWidget>[];
  if (environment == 'prod') {
    return base;
  }
  throw StateError('Unknown environment: $environment');
}
