name: celest_core
on:
  pull_request:
    paths:
      - ".github/workflows/celest_core.yaml"
      - "packages/celest_core/**"

# Prevent duplicate runs due to Graphite
# https://graphite.dev/docs/troubleshooting#why-are-my-actions-running-twice
concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}-${{ github.ref == 'refs/heads/main' && github.sha || ''}}
  cancel-in-progress: true

jobs:
  analyze_and_format:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Git Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # 4.1.1
      - name: Setup Flutter
        uses: subosito/flutter-action@62f096cacda5168a3bd7b95793373be14fa4fbaf # 2.13.0
        with:
          cache: true
      - name: Get Packages
        working-directory: packages/celest_core
        run: dart pub get
      - name: Analyze
        working-directory: packages/celest_core
        run: dart analyze
      - name: Format
        working-directory: packages/celest_core
        run: dart format --set-exit-if-changed .
          cache: true
  test_darwin:
    needs: analyze_and_format
    runs-on: macos-13-large
    timeout-minutes: 10
    steps:
      - name: Git Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # 4.1.1
      - name: Setup Flutter
        uses: subosito/flutter-action@62f096cacda5168a3bd7b95793373be14fa4fbaf # 2.13.0
        with:
          cache: true
      - name: Get Packages
        working-directory: packages/celest_core
        run: dart pub get
      - name: Test
        working-directory: packages/celest_core
        run: dart test
      - name: Get Packages (Example)
        working-directory: packages/celest_core/example
        run: flutter pub get
      - name: Setup iOS Simulator
        uses: aws-amplify/amplify-flutter/.github/composite_actions/launch_ios_simulator@main
        with:
          ios-version: 17
      - name: Test (iOS)
        working-directory: packages/celest_core/example
        run: flutter test -d iPhone integration_test/secure_storage_test.dart
      - name: Test (macOS)
        working-directory: packages/celest_core/example
        run: flutter test -d macos integration_test/secure_storage_test.dart
  test_android:
    needs: analyze_and_format
    runs-on:
      labels: linux
    timeout-minutes: 15
    steps:
      - name: Git Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # 4.1.1
      - name: Setup Flutter
        uses: subosito/flutter-action@62f096cacda5168a3bd7b95793373be14fa4fbaf # 2.13.0
        with:
          cache: true
      - name: Get Packages
        working-directory: packages/celest_core/example
        run: flutter pub get
      - name: Test (Android)
        uses: aws-amplify/amplify-flutter/.github/composite_actions/launch_android_emulator@main
        with:
          # Matches `package:jni` compileSdkVersion
          # https://github.com/dart-lang/native/blob/001910c9f40d637cb25c19bb500fb89cebdf7450/pkgs/jni/android/build.gradle#L57C23-L57C25
          api-level: 31
          arch: x86_64
          script: |
            cd packages/celest_core/example
            flutter test -d sdk integration_test/secure_storage_test.dart
