name: celest_cloud_core
on:
  pull_request:
    paths:
      - ".github/workflows/celest_cloud_core.yaml"
      - "services/celest_cloud_core/**"

# Prevent duplicate runs due to Graphite
# https://graphite.dev/docs/troubleshooting#why-are-my-actions-running-twice
concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}-${{ github.ref == 'refs/heads/main' && github.sha || ''}}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Git Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # 5.0.0
      - name: Setup Flutter
        uses: subosito/flutter-action@fd55f4c5af5b953cc57a2be44cb082c8f6635e8e # 2.21.0
        with:
          cache: true
      - name: Get Packages
        working-directory: services/celest_cloud_core
        run: dart pub upgrade
      - name: Analyze
        working-directory: services/celest_cloud_core
        run: dart analyze
      - name: Format
        working-directory: services/celest_cloud_core
        run: dart format --set-exit-if-changed .
      - name: Test
        working-directory: services/celest_cloud_core
        run: dart test
