name: celest_core
on:
  pull_request:
    paths:
      - ".github/workflows/celest_core.yaml"
      - "packages/celest_core/**"

# Prevent duplicate runs due to Graphite
# https://graphite.dev/docs/troubleshooting#why-are-my-actions-running-twice
concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}-${{ github.ref == 'refs/heads/main' && github.sha || ''}}
  cancel-in-progress: true

jobs:
  analyze_and_format:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Git Checkout
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # 4.1.2
      - name: Setup Flutter
        uses: subosito/flutter-action@44ac965b96f18d999802d4b807e3256d5a3f9fa1 # 2.16.0
        with:
          cache: true
      - name: Get Packages
        working-directory: packages/celest_core
        run: dart pub get
      - name: Analyze
        working-directory: packages/celest_core
        run: dart analyze
      - name: Format
        working-directory: packages/celest_core
        run: dart format --set-exit-if-changed .
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Git Checkout
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # 4.1.2
      - name: Setup Flutter
        uses: subosito/flutter-action@44ac965b96f18d999802d4b807e3256d5a3f9fa1 # 2.16.0
        with:
          cache: true
      - name: Get Packages
        working-directory: packages/celest_core
        run: dart pub get
      - name: Test
        working-directory: packages/celest_core
        run: dart test
      - name: Test (Chrome, dart2js)
        working-directory: packages/celest_core
        run: dart test -p chrome
      - name: Test (Chrome, dart2wasm)
        working-directory: packages/celest_core
        run: dart test -p chrome -c dart2wasm
