# Verifies the functionality of the headless wrapper scripts.
name: celest_cli (Headless)
on:
  pull_request:
    paths:
      - ".github/workflows/celest_cli.headless.yaml"
      - "apps/cli/tool/linux/**"

# Prevent duplicate runs due to Graphite
# https://graphite.dev/docs/troubleshooting#why-are-my-actions-running-twice
concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}-${{ github.ref == 'refs/heads/main' && github.sha || ''}}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-24.04-arm
        # Test multiple shells since small nuances exist between them
        shell:
          - sh
          - bash
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    defaults:
      run:
        shell: ${{ matrix.shell }}
        working-directory: apps/cli/tool/linux
    steps:
      - name: Git Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # 5.0.0
      - name: Setup Dart
        uses: dart-lang/setup-dart@e51d8e571e22473a2ddebf0ef8a2123f0ab2c02c # 1.7.1
      - name: Install Celest
        run: ./install
      - name: Verify Celest
        run: ./check
