name: distroless
publish_to: none

environment: 
  sdk: ^3.7.0

dependencies:
  async: ^2.13.0
  file: ^7.0.1
  http: ^1.3.0
  json_annotation: ^4.9.0
  logging: ^1.3.0
  meta: ^1.16.0
  pub_semver: ^2.2.0

dev_dependencies:
  build_runner: ^2.4.15
  json_serializable: ^6.9.5
